In [1]:
import numpy as np

#### 1 生成1维及2维矩阵

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b=np.array([1,2,3,4,5,6])
b

array([1, 2, 3, 4, 5, 6])

In [9]:
b=b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

#### 2、索引  
* arr[row,columns]  
row是行  
columns是列  
均从0开始

In [10]:
b[1]

array([4, 5, 6])

In [11]:
b[1,2]

6

#### 3、创建一个经纬度二维数组

In [12]:
A=np.array([40.1,120.1,42.5,139.6])

In [13]:
B=A.reshape((2,2))
B

array([[  40.1,  120.1],
       [  42.5,  139.6]])

In [14]:
B[0]

array([  40.1,  120.1])

In [15]:
B[1]

array([  42.5,  139.6])

#### 4、生成坐标系字典

In [28]:
dic=dict()

In [29]:
dic

{}

In [30]:
c=B.tolist()
c

[[40.1, 120.1], [42.5, 139.6]]

In [31]:
dic.setdefault('E01',c)

[[40.1, 120.1], [42.5, 139.6]]

In [32]:
dic['E01']

[[40.1, 120.1], [42.5, 139.6]]

#### 5、转成json格式

In [33]:
import json

In [34]:
json.dumps(dic)

'{"E01": [[40.1, 120.1], [42.5, 139.6]]}'